import "./globals.scss";
import "antd/dist/reset.css";

export const metadata = {
  title: "Event Engage Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
