import "./globals.scss";
import "antd/dist/reset.css";
import { Montserrat } from "next/font/google";

const montSerrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={montSerrat.className}>
      <body>{children}</body>
    </html>
  );
}
